apiVersion: apps/v1
kind: Deployment
metadata: 
 name: myapp7
 namespace: tgindia
spec:
 replicas: 4
 selector:
  matchLabels:
   app: nginx
   env: prod
 template:
  metadata:
   labels:
    app: nginx
    env: prod
  spec:
   containers:
     - name: nginx
       image: nginx:1.14 
       ports:
        - containerPort: 80
