apiVersion: v1
kind: Service
metadata: 
 name: tgservice
 namespace: tgindia
spec:
  type: NodePort
  selector:
   env: prod
  ports:
    - protocol: TCP
      port: 80   # Service port
      targetPort: 80 # Pod port
      nodePort: 31000  # Worker Node Port  

